version: '3'

services:
  db2:
    container_name: mssql-server-2017
    build:
      context: .
      dockerfile: Dockerfile-2017
    hostname:
        sql2017
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./backup:/var/opt/mssql/backup
    ports:
      - "1433:1433"
