version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./data:/docker-entrypoint-initdb.d # This will import DB data from an sql file in your /data folder
            - ./data/migrate.sql:/docker-entrypoint-initdb.d/data/migrate.sql # run sql commands in migrate.sql to update site urls in DB
        restart: always
        ports:
            - "3400:3306" 
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: password
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "3500:80" 
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306 
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        volumes: 
            - ./wp-content/plugins:/var/www/html/wp-content/plugins 
            - ./wp-content/uploads:/var/www/html/wp-content/uploads 