version: '3.3'
services:
   jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     ports:
      - 8081:8080
      - 50000:50000
     container_name: jenkins
     volumes:
       - /docker-volumes/jenkins/jenkins_configuration:/var/jenkins_home
       - /usr/bin/docker:/usr/bin/docker
       - /var/run/docker.sock:/var/run/docker.sock
