version: '2.2'
services:
  mongo:
    image: mongo:3.4
    container_name: unifi_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - ./db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
      #- vlan710
    restart: always
    volumes:
      - ./data:/unifi/data
      - ./log:/unifi/log
      - ./cert:/unifi/cert
      - ./init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8585:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - ./log:/unifi/log

networks:
  unifi:

  # Vlan donde pasa el tráfico wireless  
  # vlan710:
  #   driver: macvlan
  #   driver_opts:
  #     parent: vlan710
  #   ipam:
  #     config:
  #       - subnet: 10.60.0.0/16
  #         gateway: 10.60.1.1






